service: boilerplate-python-ddd

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

plugins:
  - serverless-python-requirements

functions:
  create_user:
    handler: src/lambdas/user/create_user.handler
    events:
      - http:
          path: users
          method: post
          cors: true

  update_user:
    handler: src/lambdas/user/update_user.handler
    events:
      - http:
          path: users/{id}
          method: put
          cors: true
